# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-07 08:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('conductor_name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=100)),
                ('bus_route_number', models.CharField(max_length=100)),
                ('teacher_incharge', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'buses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.PositiveIntegerField(unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('class_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('section', models.CharField(max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email_id', models.EmailField(max_length=254)),
                ('student_bus_stop', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('start_trip', models.DateTimeField(null=True)),
                ('end_trip', models.DateTimeField(null=True)),
                ('student_biometric_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scanapp.Bus')),
            ],
        ),
    ]
