# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_trip',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_trip',
            field=models.DateTimeField(null=True),
        ),
    ]
