# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-07 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_number',
            new_name='bus_route_number',
        ),
    ]
