# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-07 13:55
from __future__ import unicode_literals

from django.db import migrations
import scanapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='end_trip',
        ),
        migrations.RemoveField(
            model_name='student',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='student',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_trip',
        ),
        migrations.AddField(
            model_name='bus',
            name='latitude',
            field=scanapp.models.CommaSeparatedFloatField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='longitude',
            field=scanapp.models.CommaSeparatedFloatField(max_length=500, null=True),
        ),
    ]
