# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-15 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0003_emegencycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmegencyContact',
        ),
    ]
