# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
