# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161121173054 on 2017-06-18 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govt_emergency_numbers_app', '0002_auto_20170619_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GovtEmergencyContact',
        ),
    ]
